#!/usr/bin/env bash

# Update the Nginx configuration to run as the nginx user and listen on port 8080
NGINX_CONF="/etc/nginx/nginx.conf"

# Backup the original configuration file
cp $NGINX_CONF ${NGINX_CONF}.bak

# Modify the user directive
sed -i "s/#user www-data/user nginx/" $NGINX_CONF

# Modify the listen directive to use port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Change permissions
chmod 644 $NGINX_CONF

pkill apache2

# Reload Nginx to apply the changes
sudo -u nginx service nginx start
